### ISSUE TITLE
Images on my site won’t load

### ISSUE THREAD

**Issue by ANONIMNIQ** [bitnami/bitnami-docker-ghost#103]
install Ghost on Oracle Cloud with docker and Bitnami docker-compose.yml file,everything is working fine and I add the site to Cloudflare. Now in https secure connection my images are not visible on Chrome, because for some reason they are uploaded over http instead of https. I tried to add 
`GHOST_PROTOCOL=https`
 in my docker-compose.yml and that way images are uploaded over https, but this time port :80 are added to the url-s and images are not visiible because of the wrong url in the posts. I tried to add this command, but that can't help: 
`sudo docker exec -it ghost_ghost_1 ghost config url https://mydomainname.com`

I'm not sure how to configure this to work properly and to upload images with https without problems.

**Comment by andresbono** [comment]
Hi @ANONIMNIQ, thanks for filling this issue. Could you please share the docker-compose.yml that you are using?
