### ISSUE TITLE
Upgrade to Ghost 4.0

### ISSUE THREAD

**Issue by ChipWolf** [bitnami/bitnami-docker-ghost#107]
[Ghost 4.0](https://ghost.org/changelog/4/) is [released](https://github.com/TryGhost/Ghost/releases), this is a FR to upgrade this image when able.

**Comment by Mauraza** [comment]
Hi @ChipWolf, 

We are working to release the new version, we will update the thread when that is done.

**Comment by patpadgett** [comment]
Thanks for the Bitnami docker image.  I have used it for a while, but I am itching to upgrade... so I am moving to the official Docker image @ docker-library/ghost.

**Comment by robertwt7** [comment]
Yay, waiting for this and k8s chart. Thanks for the great work!

**Comment by iamtk** [comment]
Without sounding ungrateful can I ask is there any time frame on this update of the image to v4?
If any help is needed testing or updating please say, happy to help where I can.

**Comment by Mauraza** [comment]
Sorry, I can't give you an estimate but we are working on it. We will update this thread when v4 is released.

**Comment by Mauraza** [comment]
Hi @iamtk, @robertwt7, and @ChipWolf,

Bitnami Ghost 4.x has just been released!!

**Comment by Bluefitdev** [comment]
Awesome! Thanks so much, upgrading now
