### ISSUE TITLE
GHOST Change config.production.json on update, or even manually? New SMTP Key

### ISSUE THREAD

**Issue by jotcodeofficial** [bitnami/bitnami-docker-ghost#110]
So I ran into this problem a few days ago, whereby I had to change my transaction email API key.
I then updated my ghost helm chart and thought all was well. 

That was until I noticed that I couldn't sign up a test user to the site, and was getting a 550 error, indicating an error with the SMTP settings. 

from console on browser:
`/members/api/send-magic-link/ [HTTP/2 500 Internal Server Error`

error from the pod itself after checking the logs via: 
`kubectl logs <pod-name> -n <namespace>`

```
NAME: EmailError
MESSAGE: Failed to send email. Reason: Message delivery failed: 550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements.
```

So I listed the ENV variables of the pod itself by running:
`kubectl -n <namespace> exec <pod_name> -- env`

This showed me a different value for the API key than I have changed for the upgrade via the helm values file.
So then I went searching for a solution.

I exec'd into the container:
`
kubectl exec -it <pod-name>  /bin/bash -n <namespace>   `

I tried to directly edit the **config.production.json** which was inside the container, but it said it was a symlink.
I tried to directly edit the file but it does not have nano or vim, and it does not have admin permissions, plus I am not sure even editing it directly would work as it might need to be restarted.
I also tried to download it so I could edit/upload but same issue. 

This let me with the only remaining option I could find, exec into the container, backup all the folders in content (and blog settings just in case) via:

`kubectl cp <pod-name>:content/images ./images -n <namespace>`

The folders that I downloaded to backup are:
**apps
data
images
settings
themes**

then delete the PVC and PV for the ghost blog:
```
kubectl delete pvc <pvc-name> -n <namespace>
kubectl delete pv <pv-name> -n <namespace>
```

and then reinstall the volume and redeploy the blog again and then reupload the backup folders to the content folder:

`kubectl cp ./images <pod-name>:content/images -n <namespace>`

Now sure this works, but it is a headache. A headache that will have to happen every time I change my SMTP API key.
Is there anyway we can just change the **config.production.json** file during an upgrade? Or maybe I am doing something stupid and making things more complicated than they have to be!

Related issues:

https://github.com/bitnami/bitnami-docker-ghost/issues/93
https://github.com/bitnami/bitnami-docker-ghost/issues/105
https://github.com/bitnami/bitnami-docker-ghost/issues/102

**Comment by miguelaeh** [comment]
Hi @jotcodeofficial ,
I think the issue could be related to the container persistence. Since it is persisting the old configuration, after the upgrade it will recover the old configuration, i.e, the API key will probably be the old one. We would need to re-generate the configuration again with the new parameters.
A possible solution, but I did not test it, could be to mount an extraConfigMap as the configuration file. In that case you could edit the configmap when needed and ghost should be able to take the change

**Comment by jotcodeofficial** [comment]
> Hi @jotcodeofficial ,
> I think the issue could be related to the container persistence. Since it is persisting the old configuration, after the upgrade it will recover the old configuration, i.e, the API key will probably be the old one. We would need to re-generate the configuration again with the new parameters.
> A possible solution, but I did not test it, could be to mount an extraConfigMap as the configuration file. In that case you could edit the configmap when needed and ghost should be able to take the change

Seems like a good solution, is this something that could be added to the helm chart?

**Comment by miguelaeh** [comment]
Hi @jotcodeofficial ,
The `extraConfigMap` is something that is already supported the chart

**Comment by jotcodeofficial** [comment]
> `extraConfigMap`

So I see in the values file:

```
## Name of a ConfigMap containing extra env vars
##
extraEnvVarsConfigMap:
```

What I meant was could this be set as  default for the helm chart, not as an optional addition to be done by the user?
What are the benefits to not having this as standard?

**Comment by miguelaeh** [comment]
Ah, sorry I misunderstood the question.
I think yes, maybe we could add the config map mounted by default. But we would need to manage with issues if we want to persist the rest of the data and they are in the same folder since mounting config maps inside mounted volumes usually produces issues.
Also, we would need to maintain the configuration file in both the Helm Chart and the ghost image separatelly.

**Comment by jotcodeofficial** [comment]
> Ah, sorry I misunderstood the question.
> I think yes, maybe we could add the config map mounted by default. But we would need to manage with issues if we want to persist the rest of the data and they are in the same folder since mounting config maps inside mounted volumes usually produces issues.
> Also, we would need to maintain the configuration file in both the Helm Chart and the ghost image separatelly.

I see, I will leave that decision up to you and the team in that case, thanks for all the info!
