### ISSUE TITLE
When adding a new tag, you must restart the docker to have it visible.

### ISSUE THREAD

**Issue by bershatsky** [bitnami/bitnami-docker-ghost#111]
If you click the link to your newly created tag, you’ll get a 404 error.

restarting the docker corrects this problem, but you shouldn’t have to restart the docker for every new tag created.

**Comment by migruiz4** [comment]
Hi @bershatsky,

It is possible that this is an issue with Ghost and not the Docker image itself.

I found a recent post in Ghost forums reporting the same problem: https://forum.ghost.org/t/new-tag-404-this-happens-on-a-new-fresh-install-or-docker/23824

It would be helpful if you could provide more information, such as steps to reproduce your issue, error logs and information about your deployment (method used to deploy Ghost and configuration).

That way we could try to reproduce your issue and determine if it is a problem with Ghost or the docker image.
