### ISSUE TITLE
Bitnami Ghost v4 image stuck on 4.7.0-debian-10-r10 release?

### ISSUE THREAD

**Issue by iamtk** [bitnami/bitnami-docker-ghost#112]
Ghost has now released 4.8.0, 4.8.1, 4.8.2 and 4.8.3 (4 days ago) - have the recent automated Bitnami build's failed?

**Comment by juan131** [comment]
Hi @iamtk 

We're conscious of this issue and we're working on release new versions of the images. As you mentioned, our CI/CD pipeline failed while releasing these new versions and we're working on adapting our image and tests to the latest changes.

We'll notify you as soon as there's a new version available. Thanks for your consideration and patience.

**Comment by juan131** [comment]
Hi @iamtk 

We just released the latest version of the Ghost container `4.8.4`, see:

- https://github.com/bitnami/bitnami-docker-ghost/releases/tag/4.8.4-debian-10-r0

I'm afraid that we won't be able to release the missing `4.8.0`, `4.8.1`, `4.8.2` and `4.8.3` versions. Please feel free to reopen the issue if you find issues in the upgrade process.
