### ISSUE TITLE
Breaking changes for filesystem paths when extending the image

### ISSUE THREAD

**Issue by zoomoid** [bitnami/bitnami-docker-ghost#114]
**Description**

Commit 6a54be6ba1c1b843e60896da0837f8823ca89e4d introduced a lot of undocumented changes, which also were breaking for images that used to extend the bitnami ghost image. Most importantly, the locations of entrypoint script and configuration files were changed without further notice in commit messages, README, or tags.

**Steps to reproduce the issue:**

1. Attempt to follow the extension guide for the image in README.md

**Describe the results you received:**

After a lot of exploration in both the repository and the filesystem inside the container, I found the mismatches between the paths, which were introduced without further notice.

**Describe the results you expected:**

Please update the paths used in the README guides for extending the image, as these still use the old `/app-entrypoint.sh` script location and `/bitnami/ghost` path for the production configuration file, all of which are now located inside either `/opt/bitnami/scripts/ghost` or `/opt/bitnami/ghost`. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`(Local):

```
Docker version 20.10.5, build 55c4c88
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 18
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: FKYC:DWHN:RYGO:UOYW:IIUH:NQCO:KWWQ:VL34:BMTZ:2YVJ:EYA7:RWHB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Local Docker installation, remote Docker-in-Docker GitLab Runner, Kubernetes Cluster (v1.21)

**Comment by zoomoid** [comment]
Also, using the Tutorial to extend the docker image, the (new) script for detecting a stateful installation requires the directory mentioned in the tutorial to be empty to assume a fresh installation. This assumption is wrong, as our application state is moved outside the container except for the bucket plugin, which is installed statically inside the Dockerfile

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out. 
  Now you can mount your own init scripts in /docker-entrypoint-init.d and they will be executed in `entrypoint.sh` after all the setup is done and before the server is started (`run.sh`).
  Could you give it a try  ?

**Comment by zoomoid** [comment]
The issue with our existing deployment is that the setup function fails due to an already existing state in the (remote) database, hence the `curl` call to setup fails, but when starting with `GHOST_SKIP_BOOTSTRAP`, ghost raises an `EACCESS`:
```
Error: EACCES: permission denied, copyfile '/opt/bitnami/ghost/versions/4.9.3/core/frontend/services/settings/default-routes.yaml' -> '/opt/bitnami/ghost/versions/4.9.3/content/settings/routes.yaml'
```

This seems unrelated to this issue however...

**Comment by rafariossaa** [comment]
Yes, that seems unrelated to this one.
 Do you mind opening a new one with that issue ? That way we can track better the issues and provide help in its context.
 Don't hesitate to link this issue if needed.
