### ISSUE TITLE
fix CrashLoopBackOff Kubernetes error

### ISSUE THREAD

**Issue by vipulJain05** [bitnami/bitnami-docker-ghost#117]
I used bitnami helm charts to deploy ghost on staging environment.However , my pod is not creating after many attempts.

**Description**
My pod is not running. It i showing crashLoopBackOff errror. 

**What I received =>** 
Back-off restarting failed container. 

**What I expect =>**
The pod should be running

**Version**

**- Output of `docker version`:** 
- Docker version 20.10.10, build b485636

**Additional information:**
My container is connecting to external database RDS on aws. Everytime I deploy it , it crashes.
I am following this [article](https://komodor.com/learn/how-to-fix-crashloopbackoff-kubernetes-error/) to solve the issue.

Is it due to any missing package in my docker image? Anyone please guide me.

**Comment by juan131** [comment]
Hi @vipulJain05 

Could you please share the Ghost container logs? To do so, please remove your chart release and install it again adding the parameter `--set image.debug=true` which will increase the log verbosity:

```console
$ helm uninstall ghost && kubectl delete pvc ghost
$ helm install ghost bitnami/ghost  --set image.debug=true ...
```

> The commands above assume you used `ghost` as the name of you chart release

I also recommend you to take a look to our [Troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/).

**Comment by vipulJain05** [comment]
Can you please guide me how to deploy this ghost helm chart on my eks cluster from scratch. Currently I have two files ghost.yaml and another is ingress.yaml file. 

**ghost.yaml**
(This file is encrypted)

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: ghost
    namespace: staging
    annotations:
        fluxcd.io/automated: "true"
spec:
    releaseName: ghost
    interval: 5m
    chart:
        spec:
            chart: ghost
            version: 15.0.11
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: kube-system
    values:
        livenessProbe:
            enabled: false
        readinessProbe:
            enabled: false
        allowEmptyPassword: false
        image:
            debug: true
        ghostHost: *********************
        ghostPath: /****/
        ghostProtocol: https
        ghostUsername: **********@gmail.com
        ghostPassword: ****************
        ghostEmail: ***********@gmail.com
        # External database to use
        externalDatabase:
            host: **************************
            port: *************
            user: ******
            password: ***************
            database: *************
            # We use an external RDS database
        mariadb:
            enabled: false
        service:
            type: NodePort
        smtpPort: ""
        smtpFromAddress: ""
        smtpHost: ""
        smtpUser: ""
        smtpPassword: ""
        smtpService: ""
        storage:
            active: s3
            s3:
                accessKeyId: *********************
                secretAccessKey: *********************
                region: us-east-2
                bucket: ***********************
                signatureVersion: v4
                serverSideEncryption": AES256
                acl: public-read

**ingress.yaml**

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        alb.ingress.kubernetes.io/certificate-arn: **********************************************
        alb.ingress.kubernetes.io/group.name: staging
        alb.ingress.kubernetes.io/group.order: "1"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        helm.fluxcd.io/antecedent: staging:helmrelease/ghost
        kubernetes.io/ingress.class: alb
    finalizers:
    - group.ingress.k8s.aws/staging
    generation: 1
    labels:
        app.kubernetes.io/instance: *****
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ghost
    name: ghost
    namespace: staging
spec:
    rules:
    -   host: *************************
        http:
            paths:
            -   backend:
                    serviceName: *****
                    servicePort: 80
                path: /*****/
                pathType: ImplementationSpecific
    -   host: www*********************
        http:
            paths:
            -   backend:
                    serviceName:*****
                    servicePort: 80
                path: /*****/*
                pathType: ImplementationSpecific


And then I'm pushing these files to my master and then in the k9s , look for the deployments. Deployment is successful. Helmrelease is successfull. But the pod shows CrashLoopBackOff error and in the logs
 (Backoff restarted container).

**Comment by vipulJain05** [comment]
> Hi @vipulJain05
> 
> Could you please share the Ghost container logs? To do so, please remove your chart release and install it again adding the parameter `--set image.debug=true` which will increase the log verbosity:
> 
> ```
> $ helm uninstall ghost && kubectl delete pvc ghost
> $ helm install ghost bitnami/ghost --set image.debug=true ...
> ```
> 
> > The commands above assume you used `ghost` as the name of you chart release
> 
> I also recommend you to take a look to our [Troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/).

I tried but still getting same error
<img width="1400" alt="Screenshot 2021-11-24 at 5 26 13 PM" src="https://user-images.githubusercontent.com/47937063/143234190-72482025-6c12-4b35-91be-2c470a55980c.png">
