### ISSUE TITLE
NO PERMISSION ERROR IN GHOST

### ISSUE THREAD

**Issue by vipulJain05** [bitnami/bitnami-docker-ghost#118]
Currently ,I have ghost running at 4.7.0 version  which I installed using bitnami helm chart version 13.0.14. I am trying to upgrade my ghost version to 4.15.1 on AWS EKS from 13.0.14 to 14.0.18 using helm chart but the container is failing and giving CrashLoopBackOff error.  Attaching the logs of ghost container which is giving permission error.
![Screenshot 2021-12-01 at 9 36 13 AM](https://user-images.githubusercontent.com/47937063/144170718-be2734cb-ea55-4acc-b897-6837be15a635.png)

Can anyone please help to solve this issue as it is showing some permission issue which was working fine with 13.0.14 chart version and might be happening because of non-root container approach.

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-ghost#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
