### ISSUE TITLE
Pipeline failed after Ghost v4.24.0 release?

### ISSUE THREAD

**Issue by yslv** [bitnami/bitnami-docker-ghost#120]
Hi all, is there an issue with Ghost releases after 4.24.0?  Automated builds seem to have stopped, is there an easy fix?  The next release 4.25.0 is 5 days old today.

**Comment by javsalgar** [comment]
Hi,

We are finding issues when testing the solution. As soon as it is released we will let you know.

**Comment by iamtk** [comment]
Its been nearly 20 days since the Ghost version was updated.  Latest release is v4.28.0 is there anything we can do to use the latest release with the existing bitnami image? or any ideas when the issues might be resolved?

**Comment by miguelaeh** [comment]
Hi guys, the new versions are already in the pipeline, but the test are failing and that's why the release was blocked, please be patient. We release a high number of applications daily and sometimes a new version makes the tests to fail, which needs to be manually addressed

**Comment by carrodher** [comment]
I'm closing this issue since `4.24.0`, `4.31.0` and `4.32.0` were released for the 4.X branch in the last weeks
