### ISSUE TITLE
Repository stuck on Ghost version 4.37.0 (Pipeline broken?) 

### ISSUE THREAD

**Issue by iamtk** [bitnami/bitnami-docker-ghost#125]
### Name and Version

bitnami/bitnami-docker-ghost:4.37.0

### What steps will reproduce the bug?

Repository has been stuck on Ghost v4.37.0.  This release is now 23 days old and Ghost is currently on v4.40.0.  I assume the pipeline has broken again?  I would be great if this could be looked at or if we can help?

### What do you see instead?

As above

**Comment by carrodher** [comment]
Thanks for letting us know, we are aware of this new minor version. It seems there are some changes affecting our automated test & release pipeline so some manual intervention is needed. The engineering team is already working on it. We will update this ticket once released

**Comment by iamtk** [comment]
Thank you this is now resolved.
