### ISSUE TITLE
Ghost v5 released

### ISSUE THREAD

**Issue by iamtk** [bitnami/bitnami-docker-ghost#127]
### Name and Version

bitnami/bitnami-docker-ghost

### What steps will reproduce the bug?

Ghost v5 has been released so I'm guessing the pipeline will need updating to work with this.  Ghost v5 now only supports MySQL 8 in production.

### What do you see instead?

N/A

**Comment by rafariossaa** [comment]
Hi,
  Thanks for your comments, I will warn the team about the requirements.
  Ghost 5 will be released by our CI/CD, but it will take a while.

**Comment by rafariossaa** [comment]
Hi @iamtk 
  Could you give it a try ?
