### ISSUE TITLE
Possible documentation error in README; MARIADB_USER

### ISSUE THREAD

**Issue by TalosThoren** [bitnami/bitnami-docker-ghost#30]
It seems as though one of the available variables is incorrectly documented.

`MARIADB_USER: Root password for the MariaDB.`

I would expect this to be the user you login with, and I would expect a matching MARIADB_PASSWORD variable, which does not appear on the list at all.

When I set both MARIADB_USER and MARIADB_PASSWORD with my database's admin user and password, respectively, I see that the bitnami_ghost database is created successfully after running the container. This indicates to me that both variables are required when connecting to a database endpoint that does not use default values.

**Comment by carrodher** [comment]
Hi @TalosThoren ,

You are right, this is an error in our README.md, but the application work fine. We are working to resolve it (PR: #28). 

Thank you very much for the feedback! 

Best regards,
Carlos R. Hernández
