### ISSUE TITLE
Error mount host directories as data volumes using the Docker

### ISSUE THREAD

**Issue by blackyzero** [bitnami/bitnami-docker-ghost#54]
Hi everyone,

i follow this instruction here, https://github.com/bitnami/bitnami-docker-ghost
and getting error when trying to mount host directories, error showing as below.

```
root@pink:/var/services/docker/ghost/press# docker run --name press.abc.com -p 6705:2368  --net ghost-tier  --volume /var/services/docker/ghost/press:/bitnami/ghost bitnami/ghost:latest

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
Error executing 'postInstallation': Path '/bitnami/ghost/config.js' does not exists
```

If i add "/opt", the result as below,
```
root@pink:/var/services/docker/ghost/press# docker run --name press.abc.com -p 6705:2368  --net ghost-tier  --volume /var/services/docker/ghost/press:/opt/bitnami/ghost bitnami/ghost:latest

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
ghost   INFO  ==> Creating database...
ghost   INFO  ==> Configuring host ...
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

I remove --volume, then it works normally.

Could you please advise how to fix the issue?
Thanks a lot.

**Comment by juan131** [comment]
I could not reproduce your issue. Does the directory you're using to persist your application exists in your host machine? Here are the steps I follow to successfully run the Ghost application persisting it:
 
 - Create the Directories where I will persist the Ghost application and the MariaDB database:

       $ mkdir /tmp/ghost-persistence/
       $ mkdir /tmp/mariadb-persistence/

 - Create the Docker Network

       $ docker network create ghost-tier

 - Run MariaDB container

       $ docker run -d --name mariadb -e ALLOW_EMPTY_PASSWORD=yes --net ghost-tier --volume /tmp/mariadb-persistence:/bitnami/mariadb bitnami/mariadb:latest

 - Run Ghost container:

       $ docker run --name DOMAIN -p LOCAL_PORT:2368  --net ghost-tier --volume /tmp/ghost-persistence:/bitnami/ghost bitnami/ghost:latest

**Comment by blackyzero** [comment]
thanks juan,

I follow your instruction, but still failed.
I figure out an alternative way to fix this issue, do not create any persistence folders for both mariadb and ghost, just run the command with path for parameter --volume folder location, then docker will create automatically.

**Comment by sameersbn** [comment]
@blackyzero Can you please provide some information of your docker environment such as the output of `docker version`, `docker info`, `uname -a`,  etc.

If you are using OverlayFS as the docker storage driver for docker then you should take a look at https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html 

Also please try the instructions from the [TL;DR](https://github.com/bitnami/bitnami-docker-ghost#tldr) section of the README and let us know the results?

--- 

For future reference please consider providing the requested information while creating the issue report.

**Comment by chipironcin** [comment]
Additionally, pull again the latest images:

```
docker pull bitnami/ghost:latest
docker pull bitnami/mariadb:latest
```

**Comment by blackyzero** [comment]
@sameersbn, for your info, please check below
```
root@pink:~# docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@pink:~# 
root@pink:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 95
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.71GiB
Name: pink
ID: UR47:HQXD:5QDR:CRYC:DX7M:N6M3:TQSR:45XN:GFUD:IOYC:YFRD:IZPP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
root@pink:~# uname -a
Linux pink 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@pink:~# 

```

@chipironcin , before doing a workaround and it works, i also tried to execute these commands as your recommend, but it doesn't work.
i will try again and let you know the result.

Thanks all.

**Comment by chipironcin** [comment]
I cannot reproduce it either.
Can you check the folders `/tmp/ghost-persistence/` and `/tmp/mariadb-persistence/` that you are using when launching the containers are empty?
Also check you don't have any stale docker volume related to Ghost

```
docker volume rm $(docker volume ls -qf dangling=true)
```
