### ISSUE TITLE
How to choose database in the database?

### ISSUE THREAD

**Issue by chexxor** [bitnami/bitnami-docker-ghost#57]
I'm trying to migrate from my self-managed deployment of Ghost on Heroku. In that deployment, I've modified only the config.js file. It looks like most of those settings are configurable via env vars in this docker image, which is great, but I can't see a way to choose the database used by Ghost. My MySQL instance has several databases in it - one of those is named "ghost-db", and I want to specify to use that one.

I can configure this in my config.js file by putting the database name in the "config.production.database.connection.database" property. How to configure this in your docker image?

**Comment by jotadrilo** [comment]
Hi @chexxor,

The Ghost docker image does not allow a such as advanced configuration. It implies to recognize an existing database and run Ghost against it without further configuration.

You could use your own `config.js` after initializing a dummy Ghost deployment but you could not specify the `NODE_ENV` environment variable to switch between your database profiles. 

As a workaround, you could run the docker-compose file that you found in this repository to get a Ghost deployment up and running:

```
> curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-ghost/master/docker-compose.yml > docker-compose.yml
> docker-compose up
# Once Ghost is up and running
> docker-compose down
```

Afterward, you could stop it and slightly change the docker-compose file to mount your custom `config.js`:
```
diff --git i/docker-compose.yml w/docker-compose.yml
index b2ad9de..bfec4b4 100644
--- i/docker-compose.yml
+++ w/docker-compose.yml
@@ -14,6 +14,7 @@ services:
       - '80:2368'
     volumes:
       - 'ghost_data:/bitnami'
+      - './config.js:/bitnami/ghost/config.js'
     depends_on:
       - mariadb
     environment:
```

> *NOTE:* As mentioned, only the `production` profile is taken into account. Therefore, you should rename or remove the `production` database profile and rename your `db-test` profile to `production`.

And run docker-compose again to switch.

As a Ghost user: 
 - Do you think that being able to mount your own `config.js` file is enough to accomplish your use case?
 - When migrating, what would you expect from this image to be easier? Eg: Being able to specify the `NODE_ENV` environment variable so you can switch between database profiles.

I hope it helps!

**Comment by chexxor** [comment]
Yeah, if you provide some direction to mount my own config.js in there, it would have saved me. I currently have one, so it should be easy to just drop in. I've only ever used the production env, so that `NODE_ENV` thing isn't important to me.

On the other hand, simply providing environment variables for all the options in the config.js is better for me, as I'm deploying this image to kubernetes, and those manifest files make it really easy to define env vars for a deployment.

Because this bitnami one didn't provide enough configuration options, I landed on using the [Mike325/alpine-ghost](https://github.com/Mike325/alpine-ghost) Dockerfile and config.js. I like it because it already has all the config options as env vars, and it's also easy for me to send a PR to add missing configs because it's easy to understand how those build scripts work. I can't figure out how to improve this bitnami one, so I had to make an issue rather than a PR. :-/

About the database configuration - I use a managed MySQL instance in prod/staging. It's pretty surprising that there's no way to configure this image to connect to an existing database.

So two suggestions for improvement:
- Explain how the env vars get into the Ghost configuration, which I presume must be the config.js file. If having this, I could just send a PR to add what I need.
- Explain how to mount a config.js file.

**Comment by chipironcin** [comment]
Hi @chexxor 
Thank you so much for your suggestions!
Regarding how to configure Ghost using env vars, you have a section in the README that talks about the supported variables
https://github.com/bitnami/bitnami-docker-ghost#user-content-environment-variables

About how to mount a config.js file, the application tries to initialize everytime you start the container. If it detects the application has been already initialized and persisted in the volume, it will skip the initialization.

If you want to use your custom config.js file you should let the container initialize Ghost, then replace the config file in the volume with the new one and restart the container.
Please refer to the [volumes section](https://github.com/bitnami/bitnami-docker-ghost#mount-host-directories-as-data-volumes-with-docker-compose).

I agree the documentation can be improved and I will make sure our team takes another look at it and the configuration options.

**Comment by juan131** [comment]
Hi everybody

A new revision of the Docker Image (1.17.3-r1) hast just been released and now the Bitnami Docker Drupal Image supports using an existing database.

More info at: https://github.com/bitnami/bitnami-docker-drupal#use-an-existing-database

Please feel free to use this new image and give us any feedback about this new feature.
