### ISSUE TITLE
Please bump/build/push >= 1.22.2 ASAP

### ISSUE THREAD

**Issue by josdotso** [bitnami/bitnami-docker-ghost#67]
https://github.com/TryGhost/Ghost/releases/tag/1.22.2

Without this patch, I cannot write a real post in Ghost.

https://github.com/TryGhost/Ghost-Admin/pull/1002

Related: https://github.com/TryGhost/Ghost/issues/9543

I'm using the stable/ghost helm chart.

**Comment by carrodher** [comment]
Thanks for letting us know, we're currently working on [Ghost 1.22.3](https://github.com/TryGhost/Ghost/releases/tag/1.22.3) that was released a day ago.

It should be ready as container and helm chart in the following days but I can't provide you an exact ETA.

**Comment by javsalgar** [comment]
Just a quick note to let you know we published the latest version ;)

**Comment by carrodher** [comment]
Bitnami Ghost 1.22.3 docker image released: https://github.com/bitnami/bitnami-docker-ghost/commit/0e267bde9d6da1d589b9c9b38b4383c2e37e38e7
Stable Ghost 1.22.3 chart released: https://github.com/kubernetes/charts/commit/d3c97a6e240357c8f41f770b827b4b0c92696c48
