### ISSUE TITLE
Ghost 2.0 is out

### ISSUE THREAD

**Issue by bery** [bitnami/bitnami-docker-ghost#69]
**Description**
Ghost 2.0 has been released - do you have any intentions to support version 2 releases?

Thanks,

Lukas

**Comment by marcosbc** [comment]
Hi @bery, we're aware and already working on it. We'll keep you posted on the progress!

**Comment by bery** [comment]
Hi @marcosbc,

thanks for the quick reply! That's really good news. Let me know and I will do whatever I can to help you with testing.

Lukas

**Comment by marcosbc** [comment]
Hi @bery, just wanted to let you know that the Bitnami Docker image for Ghost 2.0 was released.

**Comment by bery** [comment]
Wow, that was fast! Let me do some testing :) I will let you know if I run into any issues.

Thanks for the great work!

**Comment by bery** [comment]
Hi,

If I try to install ghost with default values.yml, the installation fails and user bn_ghost cannot connect to the database. Could you have a look please?

```
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at my-release-mariadb:3306
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful 
mysql-c ERROR [canConnect] Connection with 'bn_ghost' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server: 
MySQL command failed to run. Error:  
ERROR 1045 (28000): Access denied for user 'bn_ghost'@'10.20.2.204' (using password: YES) 
```

Lukas
