### ISSUE TITLE
Error PostInstallation ELOOP

### ISSUE THREAD

**Issue by DracoMilesX** [bitnami/bitnami-docker-ghost#75]
Trying to run the latest image but receive this error:

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues

nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 
mysql-c INFO  MySQL server listening and working at 
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...

Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/ghost/logs/ghost.log'

**Comment by andresbono** [comment]
Hi @DracoMilesX, we can't reproduce your issue. Could you give us more details about the Docker setup that you are using? Also, it would be helpful to know the exact command that you are using to run the container.

**Comment by DracoMilesX** [comment]
Hello @andresbono here is the docker run comment f or Ghost and for the database:

docker run -d \
--name=Ghost01 \
--hostname=Ghost01 \
--memory=256M \
--memory-swap=384M \
--network=Services-Communication \
--restart=always \
-v /docker/apps/ghost:/bitnami \
-p 12200:2368 \
-e GHOST_USERNAME=user \
-e GHOST_PASSWORD=pass \
-e GHOST_EMAIL=email \
-e BLOG_TITLE=title \
-e GHOST_DATABASE_NAME=dbsname \
-e GHOST_DATABASE_USER=username \
-e GHOST_DATABASE_PASSWORD='password' \
-e MARIADB_HOST=192.168.1.20 \
-e MARIADB_PORT_NUMBER=12221 \
bitnami/ghost


docker run -d \
--name=MariaDB02 \
--hostname=MariaDB02 \
--memory=512M \
--memory-swap=768M \
--network=Databases \
--restart always \
-v /docker/apps/mariadb10:/var/lib/mysql \
-p 12221:3306 \
-e MYSQL_ROOT_PASSWORD=pass \
mariadb:10 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=""

**Comment by andresbono** [comment]
Hi @DracoMilesX, thanks for sharing it with us. To narrow the issue, can you try to execute the same commands but without using the flags to use volumes?

That way we can discard that as the source of the issue.

**Comment by DracoMilesX** [comment]
Hello @andresbono without the volume tag it is indeed working (on the latest docker pull)

With the volume tag it gives a permission denied this time on mkdir /bitnami/ghost

**Comment by andresbono** [comment]
That means the container can't write in the volume that you are mounting. What are the permissions and ownership that you have in the host directory?

**Comment by DracoMilesX** [comment]
Everything is owned by root and run as root. Permission rwxr-xr-x is on the folder itself.

Usually I manually create a folder like /docker/apps/<application name> and run the docker comment. From time to time the container itself changes the permissions. 

Ex: I use a lot of containers from linuxserver as well and majority of the folders have 911:911 as owner while I never changed it myself.

**Comment by rafariossaa** [comment]
Hi @DracoMilesX ,
  Could you provide the result of the following command to check the current status of the ownership and permissions ?
  ls -lR /bitnami

Thanks forhand
Rafael Rios Saavedra

**Comment by DracoMilesX** [comment]
From host:

./ghost/ghost:
./ghost/ghost/content:
lrwxrwxrwx 1 1001 root   23 Jan  5 07:08 logs -> /opt/bitnami/ghost/logs
./ghost/ghost/content/apps:
./ghost/ghost/content/data:
./ghost/ghost/content/images:
./ghost/ghost/content/settings:
./ghost/ghost/content/themes:
lrwxrwxrwx 1 1001 root 48 Jan  5 07:08 casper -> /opt/bitnami/ghost/current/content/themes/casper

Within docker itself:

/bitnami:
total 4
drwxr-xr-x 3 1001 root 4096 Jan  5 06:08 ghost

/bitnami/ghost:
total 8
-rw-r--r-- 1 1001 root  496 Jan  5 06:08 config.production.json
drwxr-xr-x 7 1001 root 4096 Jan  5 06:08 content

/bitnami/ghost/content:
total 20
drwxr-xr-x 2 1001 root 4096 Jan  5 06:08 apps
drwxr-xr-x 2 1001 root 4096 Jan  5 07:35 data
drwxr-xr-x 2 1001 root 4096 Jan  5 06:08 images
lrwxrwxrwx 1 1001 root   23 Jan  5 06:08 logs -> /opt/bitnami/ghost/logs
drwxr-xr-x 2 1001 root 4096 Jan  5 06:08 settings
drwxr-xr-x 2 1001 root 4096 Jan  5 06:08 themes

/bitnami/ghost/content/apps:
total 0

/bitnami/ghost/content/data:
total 100
-rw-r--r-- 1 1001 root 96359 Jan  5 07:35 example.ghost.2019-01-05.json

/bitnami/ghost/content/images:
total 0

/bitnami/ghost/content/settings:
total 4
-rw-rw-rw- 1 1001 root 138 Jan  5 06:08 routes.yaml

/bitnami/ghost/content/themes:
total 0
lrwxrwxrwx 1 1001 root 48 Jan  5 06:08 casper -> /opt/bitnami/ghost/current/content/themes/casper

**Comment by rafariossaa** [comment]
Hi @gustawdaniel ,
  Sorry for the delay.

  The container we create are non-root container, that means that the process in the container is not own by root (or other user that lauch it). Our containers are run by the user 1001 and it belongs to the root group. 

  So, in order to use the bind mounts (-v) the directory ( /docker/apps/ghost) has to have mode 775. 
 Other approach will be to use [docker volumes](https://docs.docker.com/storage/volumes/), that are managed by docker and are not depedent on the directory structure. 

  For example:
```
  # docker volume create ghost_vol

  # docker run -d --name=Ghost01 --hostname=Ghost01 --memory=256M --memory-swap=384M -v ghost_vol:/bitnami -p 12200:2368 -e GHOST_USERNAME=user -e GHOST_PASSWORD=password12 -e GHOST_EMAIL=email -e BLOG_TITLE=title -e GHOST_DATABASE_NAME=dbsname -e GHOST_DATABASE_USER=username -e GHOST_DATABASE_PASSWORD='password12' -e MARIADB_HOST=192.168.200.94 -e MARIADB_PORT_NUMBER=12221 bitnami/ghost
```
  For how to manage the volumes in docker I would refer you to [docker documentation](https://docs.docker.com/storage/volumes/).

Best regards,
Rafael Rios Saavedra
