### ISSUE TITLE
Add Option to Provide From Address in SMTP Configuration

### ISSUE THREAD

**Issue by dumrauf** [bitnami/bitnami-docker-ghost#76]
Would it be possible to provide an `SMTP_FROM_ADDRESS` option in the SMTP configuration for ghost (ideally also adding it to the corresponding helm chart as well)?

Configuring the SMTP from address seems to be possible according to the ghost docs on https://docs.ghost.org/concepts/config/#from-address and is available in other environments such as described on https://docs.bitnami.com/aws/apps/ghost/configuration/configure-smtp/. However, I was unable to find such an option in the docker image.

The problem I'm facing is that installing ghost on K8s works like a charm. The `ghostHost` variable is set to something like `www.example.com` as using the apex is not available, unfortunately. As per ghost docs, the default from email address `<ghost@www.example.com>` is then used.

However, this causes problems with my email provider as only the email address `<ghost@example.com>` (note the missing www) is allowed to send emails. So, even though the SMTP credentials are correct, my email provider tells me that "I am not allowed to send as user or group <ghost@www.example.com>".

**Comment by juan131** [comment]
Hi @dumrauf 

As you can check in the link below, this image uses the env. variables described in the link below to configure SMTP settings:

https://github.com/bitnami/bitnami-docker-ghost#smtp-configuration

Those SMTP settings can be also configured on the chart using the parameters:

- smtpHost
- smtpPort
- smtpUser
- smtpPassword
- smtpService

As you mentioned there's now way to configure the `from` address easily. I created a task to add an env. variable that allows you to configure this setting. Thanks so much for reporting it.

**Comment by dumrauf** [comment]
Hi @juan131,

Thanks for implementing this enhancement.

I've deployed the latest ghost container into a GKE cluster, using a slightly enhanced `stable/ghost` Helm chart. Here, I've added the following lines
```
        {{- if .Values.smtpFromAddress }}
        - name: SMTP_FROM_ADDRESS
          value: {{ .Values.smtpFromAddress | quote }}
        {{- end }}
```
after line 123 in file https://github.com/helm/charts/blob/master/stable/ghost/templates/deployment.yaml. For the deployment via helm, I've specified
```
smtpFromAddress: ghost@example.com
```
in the corresponding `my-values.yaml` file used for customising values.

I can see the env variable being properly propagated to the rendered `deployment.yaml`. Also, inside the container, I can see that the env variable is being propagated as
```
I have no name!@<my-pod>:/opt/bitnami/ghost$ env
...
SMTP_FROM_ADDRESS=ghost@example.com
...
```

However, the container fails to start as
```
$ kubectl logs -f <my-pod>

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at how-hard-can-it-be-mariadb:3306
mysql-c INFO  MySQL server listening and working at how-hard-can-it-be-mariadb:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
Error executing 'postInstallation': You should specify host, username, password, fromAddress, and service for SMTP configuration
```

Any idea what I am doing wrong?

Thanks for all your help and the quick turn around time on this. Massively appreciated!

**Comment by juan131** [comment]
>  I've deployed the latest ghost container into a GKE cluster, using a slightly enhanced stable/ghost Helm chart. Here, I've added the following lines...

We are including that feature on this PR: https://github.com/helm/charts/pull/10522
Thanks so much for sharing it.

> Any idea what I am doing wrong?

Did you specify the rest of SMTP parameters when deploying the chart.? Please note that it's mandatory to set all of them when configuring SMTP.

- smtpHost
- smtpPort
- smtpUser
- smtpPassword
- smtpFromAddress
- smtpService

> Thanks for all your help and the quick turn around time on this. Massively appreciated!

You're welcome! You're feedback is really appreciated since it helps us to improve our images.

**Comment by juan131** [comment]
I was unable to reproduce that issue using the latest image. These are the steps I followed:

- Install chart indicating smtp parameters:

```
$ helm install --name ghost stable/ghost \
  --set smtpHost=smtp.gmail.com \
  --set smtpPort=587 \
  --set smtpUser=XXXXX@gmail.com \
  --set smtpPassword=XXXXXX \
  --set smtpFromAddress=juan@bitnami.com \
  --set smtpService=gmail \
  --set image.pullPolicy=Always \
  --set service.type=ClusterIP
```

- Check content of the config.production.json file:

```
$ kubectl exec $(kubectl get pods -l app=ghost-ghost -o jsonpath='{.items[0].metadata.name}') cat /opt/bitnami/ghost/config.production.json | jq .mail
{
  "from": "juan@bitnami.com",
  "transport": "SMTP",
  "options": {
    "host": "smtp.gmail.com",
    "port": "587",
    "service": "gmail",
    "auth": {
      "user": "XXXXXX@gmail.com",
      "pass": "XXXXXX"
    }
  }
}
```

As you can check the field "from" is set as expected.

**Comment by dumrauf** [comment]
Hi @juan131,

Thanks for looking into this.

I can confirm that the above steps work and do add the `from` address to the `config.production.json`.

I get the feeling that the
```
helm repo update
```
did the trick in the end as my local helm charts cache seemed to be out of date.

This solves my problem and leaves me to thank you for all your support and quick turn around times!

**Comment by juan131** [comment]
Hi @dumrauf 

I'm glad you could get it working!! 

Please do not hesitate to let us know if you face any issue in the future with this or any other Bitnami container image or Helm chart.

**Comment by thodquach** [comment]
Could anyone please help me take a look my issue?
I can not configure the SMTP, after i set all of SMTP env variable
```
https://github.com/bitnami/bitnami-docker-ghost/issues/86
```

Tks in advance !!!
