### ISSUE TITLE
Feature Request: Configurable ghost listen port

### ISSUE THREAD

**Issue by bobthemac** [bitnami/bitnami-docker-ghost#85]
I have been setting up some images of docker and run into a feature I don't think exists and there looks to be no clear way around it. I am using nginx-proxy and the ssl-companion and it links in with the first ghost container fine, the problem is every subsequent instance also listens on the same port so when you go to the web address it takes you to the wrong instance. 

A way of configuring this ghost port would allow for easy usage of multiple ports and allow for multiple independent instances.

**Comment by miguelaeh** [comment]
Hi @bobthemac ,
Try using the `GHOST_PORT_NUMBER` env var?
To see all the env available env vars for Ghost you can check this file https://github.com/bitnami/bitnami-docker-ghost/blob/master/3/debian-10/rootfs/ghost-inputs.json

**Comment by bobthemac** [comment]
I believe that that `GHOST_PORT_NUMBER` is used for building URL's I had to set it to fix a SSL issue by default it is set to 80 but for SSL obviously it needs to be 443. This has no impact on the `2368` port used by ghost to listen for connections, I think its hard coded into the Dockerfile as that manually references `2368` as the port to expose.

This issue talks about ghost port number https://github.com/bitnami/bitnami-docker-ghost/issues/78

**Comment by miguelaeh** [comment]
Hi @bobthemac ,
You are right, sorry for the confusion.
Thank you very much for reporting we will release a new image with an option to configure that port when we have the time.
