### ISSUE TITLE
Can not configure SMTP mail part 

### ISSUE THREAD

**Issue by thodquach** [bitnami/bitnami-docker-ghost#86]
**Description**

**Steps to reproduce the issue:**
Firstly, I want to say thanks because your Ghost image is so amazing and wonderful. 
I can use helm to install Ghost on a K8s cluster, below is the official chart from helm repository, this chart use bitnami-docker-ghost images build from your repo.
```
https://github.com/helm/charts/tree/master/stable/ghost
```
After i have installed Ghost successfully on our k8s cluster, but i can not configure the SMTP mail part:
Initially, i dont set anythings related to SMTP mail, the env variable just like this:
```
{
  "database": {
    "client": "mysql",
    "connection": {
      "host": "x.x.x.x",
      "port": 3306,
      "password": "123456789",
      "user": "ghost_user",
      "database": "ghost_db"
    }
  },
  "url": "http://ghost-dev.xxx.dev/",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file"
    ]
  },
  "process": "local",
  "paths": {
    "contentPath": "/opt/bitnami/ghost/content"
  }

```
What is `  "mail": { "transport": "Direct" },`?

**Describe the results you received:**
I set all of SMTP env variable like this:
```
I have no name!@ghost-dev-d9676d49-lbrqk:/opt/bitnami/ghost$ env | grep SMTP
SMTP_SERVICE=SendGrid
SMTP_PORT=2525
SMTP_PASSWORD=xxx
SMTP_USER=apikey
SMTP_FROM_ADDRESS=no-reply@example.com
SMTP_HOST=smtp.sendgrid.net
```
But the configure json file still same to before (Initial), nothings change.
```
{
  "database": {
    "client": "mysql",
    "connection": {
      "host": "x.x.x.x",
      "port": 3306,
      "password": "123456789",
      "user": "ghost_user",
      "database": "ghost_db"
    }
  },
  "url": "http://ghost-dev.xxx.dev/",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file"
    ]
  },
  "process": "local",
  "paths": {
    "contentPath": "/opt/bitnami/ghost/content"
  }

```
**Describe the results you expected:**
I have read about the SMTP mail part in Ghost document and i think have somethings wrong here, because if it work we will have the mail part similar to in below Ghost document.
```
https://ghost.org/docs/concepts/config/
```
```
"mail": {
    "transport": "SMTP",
    "options": {
        "service": "Mailgun",
        "host": "smtp.eu.mailgun.org",
        "port": 465,
        "secureConnection": true,
        "auth": {
            "user": "postmaster@example.mailgun.org",
            "pass": "1234567890"
        }
    }
}
```

1. I have configure in wrong way
2. The config related to SMTP does not work

Could you please help me take a look? 
I can not send mail to invite people to use out new set up Ghost.
And i can not find the reference document for 
```
https://github.com/bitnami/bitnami-docker-ghost/blob/master/3/debian-10/rootfs/ghost-inputs.json
```

Tks in advance !!!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `stable/ghost` chart version: 9.1.4

- Output of `helm` version:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
- Output of `docker-compose version` (if applicable):

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Did you try deploying a new chart with the smtp values set from the beginning? Maybe it is an issue with the persistence, that simply doesn't reconfigure itself.

**Comment by thodquach** [comment]
Hello @javsalgar ja,
Yes i meet the issue with the persistence. I need to `helm delete --purge <release>` and re-configure to make it works.
Do you think we dont need to use the persistence:
```
persistence:
  enabled: false
```
Tks so much =))))

**Comment by michaeljguarino** [comment]
This issue should not have been closed, we shouldn't have to wipe our ghost instance to reconfigure smtp settings.

**Comment by javsalgar** [comment]
I agree that, in this kind of scenarios where it requires a configuration file, there should be an alternative to this. We are working on, for example, allowing custom scripts to be run on every system restart. Of course, I think that the SMTP settings could be always reconfigured regardless of first boot or subsequent boots.

**Comment by michaeljguarino** [comment]
The ghost official docker image permists configuring every field via env var as well, I'm not sure if the bitnami image also allows that considering how much is meddled with in the entrypoint of the image.

**Comment by javsalgar** [comment]
I'll forward this to the engineering team

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-ghost#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
