### ISSUE TITLE
Optional smtpService config

### ISSUE THREAD

**Issue by S8Cloud** [bitnami/bitnami-docker-ghost#90]
**Description**

Currently, all the following envs must be configured:
```
smtpFromAddress
smtpHost
smtpPassword
smtpPort
smtpService
smtpUser
```
Otherwise it will fail to install.
```
Error executing 'postInstallation': You should specify host, username, password, fromAddress, and service for SMTP configuration
```
However, according to [Ghost Doc](https://ghost.org/docs/concepts/config/#mail) and [nodemailer 0.7](https://github.com/nodemailer/nodemailer/tree/0.7/#setting-up-smtp) which ghost use, the `Service` config is optional.

> service - an optional well known service identifier ("Gmail", "Hotmail" etc., see Well known Services for a list of supported services) to auto-configure host, port and secure connection settings

For Gmail service, it can be configured with service parameter
```
var transport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
        user: "gmail.user@gmail.com",
        pass: "userpass"
    }
});
```
or the same without service parameter
```
var transport = nodemailer.createTransport("SMTP", {
    host: "smtp.gmail.com", 
    secureConnection: true, 
    port: 465, 
    auth: {
        user: "gmail.user@gmail.com",
        pass: "userpass"
    }
});
```
Of cause, it will work if we set all the envs but seems unnecessary.
I am not using the [listed services](https://github.com/nodemailer/nodemailer/tree/0.7/#well-known-services-for-smtp), so it would be impossible to configure the `smtpService` value. My Ghost smtp looks like this:

```
  "mail": {
    "from": "user@example.com",
    "transport": "SMTP",
    "options": {
      "host": "smtp.office365.com",
      "port": 587,
      "secureConnection": true,
      "auth": {
        "user": "user@example.com",
        "pass": "userpass"
      }
    }
  }
```
Any chance to make `smtpService` optional and add the `secureConnection` value?

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input! I will open a task for evaluation. As it is not a critical feature, I cannot gurantee an ETA but we will update the ticket as soon as we have more news.

**Comment by lekspyl** [comment]
The issue is not so straightforward to identify as I was trying to configure Bitnami's Ghost Helm chart and although envvars were in place (all except `smtpFromAddress` which is optional in my case) final `config.production.json` was getting templated as:

```
  "mail": {
    "transport": "Direct"
  },
```

**Comment by javsalgar** [comment]
Hi,

We are performing major changes in several of our containers. We are transitioning from node.js to bash as the configuration language. We will make sure that, when we perform the migration to bash, these use cases get covered.

**Comment by SkYNewZ** [comment]
> Hi,
> 
> Thank you very much for the input! I will open a task for evaluation. As it is not a critical feature, I cannot gurantee an ETA but we will update the ticket as soon as we have more news.

Hello! Why do you say it's not critical? This problem prevents me from deploying Ghost `bitnami/ghost:3.35.5`.
While waiting for a fix, can you tell me what version I can deploy to avoid this?

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of the container where you can specify the secure connection parameter and where the service parameter is optional.

https://github.com/bitnami/bitnami-docker-ghost/commit/24afbd290c6aad3e058e646ed3cc17299b064581
