### ISSUE TITLE
MESSAGE: The currently active theme "yoffa_new" is missing. 

### ISSUE THREAD

**Issue by saikatharryc** [bitnami/bitnami-docker-ghost#94]
Running on k8s using helm chart,
Using the existing Database and had the installation of a ghost on the same DB.

While pointing the AWS and DB creds to the exact same one I Receive a message like
```
MESSAGE: The currently active theme "yoffa_new" is missing. 
```
which is triggered by the readiness probe (I can remove/disable that probe and probably login and upload the theme, which would be the last option)

What I'm trying to understand is, how to rebuild the image using my custom image? or probably pull it from S3 or somewhere in the run time.

I Tried to rebuild the image like this:

```
FROM bitnami/ghost:3.38.2-debian-10-r0

USER root

COPY ./yoffa_new.zip yoffa_new.zip
RUN apt-get update && apt-get install unzip -y
RUN mkdir /bitnami/ghost/content && mkdir /bitnami/ghost/content/themes && mkdir /bitnami/ghost/content/themes/yoffa_new && unzip yoffa_new.zip -d /bitnami/ghost/content/themes/yoffa_new
```
which definitely did not work, most probably because the path is in volume.

any idea or tricks or suggestion on this?
how to go ahead with the existing custom theme?

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. That volume folder will be replace with an actual volume, so the theme should not be there. My advice is to try putting it in `/opt/bitnami/ghost/content/themes`. Could you try it?

**Comment by saikatharryc** [comment]
```
RUN unzip yoffa_new.zip -d /opt/bitnami/ghost/content/themes/yoffa_new
```
does not work either,
I believe I have to raise this in the ghost community, it would be great if there is some option to pull the theme automatically.

meanwhile, if there are any tricks or workaround someone can see, I'm all ears.

incase the pod restarts, I have to upload the theme again, which is really bad.

**Comment by javsalgar** [comment]
Hi,

Doesn't the theme move to `/bitnami/ghost` after the container initialization? Does it show any error? I believe the container logic should move the theme there. Do you have the image in a public registry so I can test it?

**Comment by saikatharryc** [comment]
I do see an error:
```
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/ghost/content' -> '/opt/bitnami/ghost/content'                                                                                                   
```
here is the image: `saikatharryc/ghost:3.38.2-debian-10-r0` 
https://hub.docker.com/r/saikatharryc/ghost/tags

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue. I used this docker-compose.yml

```
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-ghost/master/docker-compose.yml
```

I could see that the theme is there

![image](https://user-images.githubusercontent.com/1133777/100719972-a3826780-33bd-11eb-9e31-b373f7e0b51c.png)


I could activate it

![image](https://user-images.githubusercontent.com/1133777/100719993-ab420c00-33bd-11eb-92c1-e899dc5d10df.png)

It seems to me that there could be an issue with existing PVCs or with the volume technology in your cluster.

**Comment by saikatharryc** [comment]
I'm still finding the issue since I'm using the same type of PV for all,
I'm now guessing some misconfiguration is in place, 

meanwhile, I would request to keep this open, just incase anyone gets the faces the same.

**Comment by javsalgar** [comment]
Hi,

Sure! I will leave it open and if the stale bot appears I will ping you in case you have more news

**Comment by javsalgar** [comment]
Any news @saikatharryc ?

**Comment by saikatharryc** [comment]
Thanks, @javsalgar , i could not find any solution so far. 
lets see, i will probably post in stackoverflow in next week and see if I get any..

**Comment by saikatharryc** [comment]
Since open for really long now, and no solution so far, closing this as of now.!
incase time-traveler digs into this and have a solution, would love to hear about how you solved this issue?
